name: DockerHub Container CI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBNAME }}
          password: ${{ secrets.DOCKERHUBCI }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nellokudo/wine-builder
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
